webtalk_init -webtalk_dir /home/huseyin/VivadoProjects/Term_Project/Term_Project.sim/UART_Receiver_Sim/behav/xsim/xsim.dir/UART_Receiver_Sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  4 21:34:05 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "22c5927a-e37f-4ad7-9af4-3adc5d770159" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fc16d83de4b14d3890103d2240108d3e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2931.625 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "7" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "30 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "4 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "59" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "21" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.28_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "274964_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1327474114 -regid "" -xml /home/huseyin/VivadoProjects/Term_Project/Term_Project.sim/UART_Receiver_Sim/behav/xsim/xsim.dir/UART_Receiver_Sim_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/huseyin/VivadoProjects/Term_Project/Term_Project.sim/UART_Receiver_Sim/behav/xsim/xsim.dir/UART_Receiver_Sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/huseyin/VivadoProjects/Term_Project/Term_Project.sim/UART_Receiver_Sim/behav/xsim/xsim.dir/UART_Receiver_Sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
